version: '2'
services:
  client:
    image: myclient:latest
    ports:
     - "80:3000"
    command: "npm --prefix /usr/src/app run start"
    volumes:
     - "./BoardDocker:/usr/src/app"
  server:
    image: myserver:latest
    ports:
     - "8000:80"
    volumes:
     - "./ApiDocker:/var/www"
  mysql:
    image: mysql
    ports:
     - "3306:3306"
    environment:
     MYSQL_ROOT_PASSWORD:
     MYSQL_DATABASE: tasksmanager
